image:
  repository: reg.nodeops.xyz/devops/reloader
  tag: vault-watcher
  pullPolicy: IfNotPresent

reloader:
  reloadStrategy: annotations           # Recommended for GitOps-friendly reloads
  vaultTrigger:
    enabled: false
    rotationToken: ""  # disabled when using watcher-only mode
  # Alternatively enable automatic polling (no webhook). Disable vaultTrigger if using watcher only.
  vaultWatcher:
    enabled: true
    address: "https://vault.nodeops.xyz"
    token: ""          # Metadata access token consider using Kubernetes auth or external secret manager
    pollInterval: "45s"
    skipTLSVerify: false
  enableMetricsByNamespace: true
  custom_annotations:
    vault: "vault.reloader.stakater.com/reload" # (optional override; keep default)
  logLevel: debug
